Repository vivien/i3blocks-contrib, pull requests merged in 2020-11, with the labels that each got.

#365 dimmer: fix config example
  dimmer/README.md
Labels: hacktoberfest-accepted

#364 wifi: exposing colors as variables
  wifi/i3blocks.conf
  wifi/wifi
Labels: enhancement, hacktoberfest-accepted

#201 rofi-calendar: navigation lines to increment and decrement month
  rofi-calendar/README.md
  rofi-calendar/rofi-calendar
  rofi-calendar/screenshot.png
Labels: enhancement

#344 Use /usr/bin/env in shebangs
  bandwidth/bandwidth
  battery/battery
  calendar/calendar
  cpu_usage/cpu_usage
  cpu_util_detailed/cpu_util_detailed
  dimmer/dimmer
  disk/disk
  docker/docker
  essid/essid
  go/go
  gpu-load/gpu-load
  iface/iface
  kubernetes/kubernetes
  load_average/load_average
  memory/memory
  nm-vpn/nm-vpn
  ssid/ssid
  tahoe-lafs/tahoe-lafs
  volume-pulseaudio/volume-pulseaudio
  wifi/wifi
  xkb_layout/xkb_layout
Labels: enhancement

#339 gpu-load: support AMD based card
  gpu-load/README.md
  gpu-load/gpu-load
Labels: enhancement

#368 openvpn-systemd: Add script to monitor openvpn through systemd
  openvpn-systemd/README.md
  openvpn-systemd/openvpn-systemd
  openvpn-systemd/openvpn-systemd.png
Labels: changes requested, enhancement, new blocklet

#372 timer_and_stopwatch: export neutral background color
  timer_and_stopwatch/README.md
  timer_and_stopwatch/timer_and_stopwatch
Labels: enhancement
