Repository vivien/i3blocks-contrib, pull requests merged in 2020-02, with the labels that each got.

#222 key_light: add script to control keyboard backlight
  README.adoc
  key_light/README.md
  key_light/i3blocks.conf
  key_light/key_light
  key_light/key_light.png
Labels: new blocklet

#246 dunst: add dunst, a do-not-disturb button for muting notifications
  README.adoc
  dunst/LICENSE
  dunst/README.md
  dunst/dunst
  dunst/dunst.gif
  dunst/i3blocks.conf
Labels: changes requested, new blocklet

#213 keyindicator: customizable ON/OFF strings
  keyindicator/LICENSE.md
  keyindicator/README.md
  keyindicator/keyindicator
  keyindicator/keyindicator-active-vs-inactive.png
  keyindicator/keyindicator-active.png
  keyindicator/keyindicator-inactive.png
Labels: changes requested, enhancement

#149 nvidia-temp: add nvidia-temp, Display temperature of NVIDIA GPU
  nvidia-temp/LICENSE
  nvidia-temp/README.md
  nvidia-temp/i3blocks.conf
  nvidia-temp/nvidia-temp
  nvidia-temp/nvidia-temp.png
Labels: changes requested, new blocklet

#215 timer_and_stopwatch: minimal stopwatch and colored timer
  timer_and_stopwatch/LICENSE.md
  timer_and_stopwatch/README.md
  timer_and_stopwatch/paused_stopwatch.png
  timer_and_stopwatch/running_timer.png
  timer_and_stopwatch/timer_and_stopwatch
Labels: changes requested, new blocklet

#303 cpu_util_detailed: Add cpu_util_detailed, print detailed CPU usage.
  cpu_util_detailed/LICENSE
  cpu_util_detailed/README.md
  cpu_util_detailed/cpu_util_detailed
  cpu_util_detailed/cpu_util_detailed.png
  cpu_util_detailed/i3blocks.conf
Labels: new blocklet

#306 nm-vpn: use interface type for status, add colors, add INIT status.
  nm-vpn/README.md
  nm-vpn/i3blocks.conf
  nm-vpn/nm-vpn
Labels: enhancement
